name: Update Prizes

on:
  push:
    branches:
      - main

jobs:
  update:   
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update prizes
        run: |
          prizes_awarded=$(jq --raw-output '.prizes_awarded + 1' ./docs/data/prizes.json)
          echo "{ \"prizes_awarded\": $prizes_awarded }" > ./docs/data/prizes.json

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./docs/data/prizes.json
          git commit -m "Update prizes"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}